apiVersion: lgpo.io/v1
kind: PolkitPolicy
metadata: { name: nm-wifi-users }
selector: { tags: { group: ["laptops"] } }
spec:
  rules:
    - name: wifi-users
      matches:
        - action_id: org.freedesktop.NetworkManager.wifi.scan
        - action_id: org.freedesktop.NetworkManager.settings.modify.own
        - action_id: org.freedesktop.NetworkManager.enable-disable-wifi
      subject: { active: true }
      result: YES
    - name: nm-default
      matches:
        - action_prefix: org.freedesktop.NetworkManager
      subject: { group: sudo }
      result: AUTH_ADMIN_KEEP
      default_result: NO
